version: '3'
services:
  app:
    image: imanilchaudhari/docker-ubuntu:22.04
    restart: 'no'
    ports:
      - '${APP_PORT}:80'
    volumes:
      - './:/var/www'
      - './docker/app/default.conf:/etc/apache2/sites-available/000-default.conf'
      - './docker/php/php.ini:/etc/php/8.1/apache2/php.ini'
      - './docker/php/php.ini:/etc/php/8.1/cli/php.ini'
    links:
      - mariadb 
      - mailhog
  mariadb:
    image: 'mariadb:10.3'
    restart: 'no'
    command: '--sql_mode=""'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  adminer:
    image: adminer
    restart: 'no'
    links:
      - mariadb
    ports:
      - '${ADM_PORT}:8080'
  mailhog:
    image: mailhog/mailhog
    restart: 'no'
    ports:
      - 1025:1025
      - 8025:8025